{"uuid":"65f7371b-accc-4659-8388-c204ba454a22","historyId":"9d25c2f28ccfb0bd196b58b5b2c908ea","fullName":"com.SeleniumTesting.ex07_Webtables.TestSelenium22.test_webtable","labels":[{"name":"package","value":"com.SeleniumTesting.ex07_Webtables.TestSelenium22"},{"name":"testClass","value":"com.SeleniumTesting.ex07_Webtables.TestSelenium22"},{"name":"testMethod","value":"test_webtable"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"SeleniumATB9x"},{"name":"subSuite","value":"com.SeleniumTesting.ex07_Webtables.TestSelenium22"},{"name":"host","value":"LAPTOP-NTSQCFSG"},{"name":"thread","value":"27192@LAPTOP-NTSQCFSG.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"test_webtable","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Index 4 out of bounds for length 4","trace":"java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4\r\n\tat java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)\r\n\tat java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)\r\n\tat java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)\r\n\tat java.base/java.util.Objects.checkIndex(Objects.java:365)\r\n\tat java.base/java.util.ArrayList.get(ArrayList.java:428)\r\n\tat com.SeleniumTesting.ex07_Webtables.TestSelenium22.test_webtable(TestSelenium22.java:29)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"Verify that with valid email, pass, error message is shown on the test_katalon_login","steps":[],"attachments":[],"parameters":[],"start":1736060950931,"stop":1736060955849}